version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: npm run start:dev api

    env_file:
      - ./apps/api/.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '2000:1000'

    restart: always

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth

    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  mno:
    build:
      context: .
      dockerfile: ./apps/mno/Dockerfile
      target: development
    command: npm run start:dev mno
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    ports:
      - 2001:2000

volumes:
  postdb-data:
    driver: local

networks:
  default:
    external:
      name: local-docker-network
