version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: npm run start:dev api

    env_file:
      - ./apps/api/.env
    volumes:
      - .:/home/app
    ports:
      - '2000:1000'

  # billing:
  #   build:
  #     context: .
  #     dockerfile: ./apps/billing/Dockerfile
  #     target: development
  #   command: npm run start:dev billing
  #   env_file:
  #     - ./apps/billing/.env
  #   depends_on:
  #     - mongodb-primary
  #     - mongodb-secondary
  #     - mongodb-arbiter
  #     - rabbitmq
  #     - auth
  #   volumes:
  #     - .:/home/app
  #     - /home/app/node_modules
  # auth:
  #   build:
  #     context: .
  #     dockerfile: ./apps/auth/Dockerfile
  #     target: development
  #   command: npm run start:dev auth
  #   ports:
  #     - '3001:3001'
  #   env_file:
  #     - ./apps/auth/.env
  #   depends_on:
  #     - mongodb-primary
  #     - mongodb-secondary
  #     - mongodb-arbiter
  #     - rabbitmq
  #   volumes:
  #     - .:/home/app
  #     - /home/app/node_modules

networks:
  default:
    external:
      name: local-docker-network